// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WebFract3D.Fractals.Mandelbrot3 = (function(_super) {
    __extends(Mandelbrot3, _super);

    function Mandelbrot3() {
      _ref = Mandelbrot3.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Mandelbrot3.prototype.calculate = function(r, i) {
      var a, zi, zr, _i, _ref1, _zi, _zr;
      zr = 0;
      zi = 0;
      for (a = _i = 0, _ref1 = this.fractal_state.max_iterations - 1; 0 <= _ref1 ? _i <= _ref1 : _i >= _ref1; a = 0 <= _ref1 ? ++_i : --_i) {
        _zr = zr * zr * zr - 3 * zr * zi * zi + r;
        _zi = 3 * zr * zr * zi - zi * zi * zi + i;
        zr = _zr;
        zi = _zi;
        if (zr * zr + zi * zi > 4) {
          return a;
        }
      }
      return a;
    };

    return Mandelbrot3;

  })(WebFract3D.Fractals.Base);

}).call(this);
