// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WebFract3D.Fractals.Newton2 = (function(_super) {
    __extends(Newton2, _super);

    function Newton2() {
      _ref = Newton2.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Newton2.prototype.poles = [[1, 0], [-1, 0]];

    Newton2.prototype.calculate = function(r, i) {
      var a, numi, numr, z2i, z2r, zi, zr, _i, _ref1, _ref2;
      zr = 10;
      zi = 10;
      z2r = r;
      z2i = i;
      for (a = _i = 0; _i <= 100000000; a = ++_i) {
        if (a > (this.fractal_state.max_iterations - 1)) {
          return [a, zr, zi];
        }
        if (this.complexDistance(zr, zi, z2r, z2i) < this.quittingDistance) {
          return [a, zr, zi];
        }
        zr = z2r;
        zi = z2i;
        _ref1 = this.complexMultiplication(zr, zi, zr, zi), numr = _ref1[0], numi = _ref1[1];
        numr -= 1;
        _ref2 = this.complexDivision(numr, numi, 2 * zr, 2 * zi), z2r = _ref2[0], z2i = _ref2[1];
        z2r = zr - z2r;
        z2i = zi - z2i;
      }
    };

    return Newton2;

  })(WebFract3D.Fractals.Base);

}).call(this);
